title: Cities without Number SRD
description: Cities without Number System Reference Document
theme: just-the-docs

url: https://sambilheimer.github.io/CWNSRDV3/

color_scheme: clr

logo: "/assets/CWN_logo.webp"
favicon_ico: /assets/images/favicon.ico

# External navigation links
nav_external_links:
  - title: WWN SRD â†—
    url: https://wwn.quadrifons.com
    hide_icon: true # set to true to hide the external link icon - defaults to false
